# Generated by Django 4.1.4 on 2023-01-01 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sa_final', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='APPID',
            field=models.CharField(max_length=20, verbose_name='app編號'),
        ),
        migrations.AlterField(
            model_name='order',
            name='C_AMOUNT',
            field=models.CharField(max_length=20, verbose_name='花費的碳稅'),
        ),
    ]
