# Generated by Django 4.1.4 on 2023-01-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sa_final', '0004_alter_order_amount_alter_order_appid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SHOPID', models.CharField(max_length=20, verbose_name='店鋪編號')),
                ('SHOPNAME', models.CharField(max_length=10, verbose_name='店鋪名稱')),
                ('ADDRESS', models.CharField(max_length=40, verbose_name='使用者地址')),
            ],
        ),
    ]
