# Generated by Django 4.1.4 on 2023-01-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sa_final', '0008_lock_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='CLIST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ORDID', models.CharField(max_length=20, verbose_name='模式名稱')),
                ('WMODE', models.CharField(max_length=20, verbose_name='洗滌模式')),
                ('LMODE', models.CharField(max_length=20, verbose_name='乾燥模式')),
                ('FMODE', models.CharField(max_length=20, verbose_name='摺衣模式')),
                ('TIME', models.IntegerField(verbose_name='總時長')),
                ('PRICE', models.IntegerField(verbose_name='總金額')),
            ],
        ),
        migrations.CreateModel(
            name='FMODE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FMODE', models.CharField(max_length=20, verbose_name='模式名稱')),
                ('MONEY', models.IntegerField(verbose_name='價格')),
                ('POINTS', models.IntegerField(verbose_name='碳權點數')),
                ('MEMISSIONS', models.IntegerField(verbose_name='碳排(公斤)')),
                ('TIME', models.IntegerField(verbose_name='所需時間(分鐘)')),
            ],
        ),
        migrations.CreateModel(
            name='LMODE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LMODE', models.CharField(max_length=20, verbose_name='模式名稱')),
                ('MONEY', models.IntegerField(verbose_name='價格')),
                ('POINTS', models.IntegerField(verbose_name='碳權點數')),
                ('MEMISSIONS', models.IntegerField(verbose_name='碳排(公斤)')),
                ('TIME', models.IntegerField(verbose_name='所需時間(分鐘)')),
            ],
        ),
        migrations.CreateModel(
            name='WMODE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WMODE', models.CharField(max_length=20, verbose_name='模式名稱')),
                ('MONEY', models.IntegerField(verbose_name='價格')),
                ('POINTS', models.IntegerField(verbose_name='碳權點數')),
                ('MEMISSIONS', models.IntegerField(verbose_name='碳排(公斤)')),
                ('TIME', models.IntegerField(verbose_name='所需時間(分鐘)')),
            ],
        ),
    ]
