# Generated by Django 4.1.4 on 2023-01-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sa_final', '0009_clist_fmode_lmode_wmode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='lock_test',
        ),
        migrations.AddField(
            model_name='clist',
            name='BAGNUM',
            field=models.IntegerField(default=1, verbose_name='袋數'),
        ),
        migrations.AlterField(
            model_name='clist',
            name='ORDID',
            field=models.CharField(max_length=20, verbose_name='訂單編號'),
        ),
    ]
