# Generated by Django 4.1.4 on 2023-01-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sa_final', '0010_delete_lock_test_clist_bagnum_alter_clist_ordid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clist',
            name='PRICE',
            field=models.IntegerField(blank=True, null=True, verbose_name='總金額'),
        ),
        migrations.AlterField(
            model_name='clist',
            name='TIME',
            field=models.IntegerField(blank=True, null=True, verbose_name='總時長'),
        ),
    ]
