# Generated by Django 4.1.5 on 2023-01-03 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sa_final', '0011_alter_clist_price_alter_clist_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clist',
            name='ORDID',
            field=models.CharField(max_length=20, null=True, verbose_name='訂單編號'),
        ),
    ]
