# Generated by Django 4.1.5 on 2023-01-04 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sa_final', '0013_alter_clist_ordid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CLIST',
        ),
    ]
