# Generated by Django 4.1.5 on 2023-01-05 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sa_final', '0015_clist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CLIST',
        ),
    ]
