# Generated by Django 4.1.5 on 2023-01-05 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sa_final', '0019_clist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CLIST',
        ),
    ]
