# Generated by Django 4.1.5 on 2023-01-05 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sa_final', '0020_delete_clist'),
    ]

    operations = [
        migrations.CreateModel(
            name='CLIST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ORDID', models.CharField(max_length=20, verbose_name='訂單編號')),
                ('BAGNUM', models.IntegerField(default=1, verbose_name='袋數')),
                ('PRICE', models.IntegerField(default=0, verbose_name='總金額')),
                ('TIME', models.IntegerField(default=0, verbose_name='總時長')),
                ('FMODE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sa_final.fmode')),
                ('LMODE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sa_final.lmode')),
                ('WMODE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sa_final.wmode')),
            ],
        ),
    ]
