# Generated by Django 4.1.4 on 2023-01-07 13:20

from django.db import migrations, models
import sa_final.models


class Migration(migrations.Migration):

    dependencies = [
        ('sa_final', '0023_clist'),
    ]

    operations = [
        migrations.CreateModel(
            name='LOGIN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FKcheck', models.CharField(default=sa_final.models.UUIDrand, max_length=36)),
                ('Rstate', models.CharField(max_length=42)),
                ('Raccesscode', models.CharField(max_length=43)),
            ],
        ),
    ]
