# Generated by Django 4.1.5 on 2023-01-10 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sa_final', '0024_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clist',
            name='FMODE',
        ),
        migrations.RemoveField(
            model_name='clist',
            name='LMODE',
        ),
        migrations.RemoveField(
            model_name='clist',
            name='WMODE',
        ),
        migrations.DeleteModel(
            name='delivery',
        ),
        migrations.DeleteModel(
            name='order',
        ),
        migrations.DeleteModel(
            name='CLIST',
        ),
    ]
