# Generated by Django 4.1.5 on 2023-01-10 14:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sa_final', '0025_remove_clist_fmode_remove_clist_lmode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ORDID', models.CharField(max_length=20, verbose_name='訂單編號')),
                ('SHOPID', models.CharField(max_length=20, verbose_name='店鋪編號')),
                ('PHONE', models.CharField(max_length=10, verbose_name='使用者電話')),
                ('ADDRESS', models.CharField(max_length=40, verbose_name='使用者地址')),
                ('GDATE', models.DateTimeField(default=django.utils.timezone.now, verbose_name='取件時間')),
                ('S_CODE', models.CharField(max_length=20, verbose_name='取件條碼')),
                ('G_CODE', models.CharField(max_length=20, verbose_name='送件條碼')),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ORDID', models.CharField(max_length=20, verbose_name='訂單編號')),
                ('MEMID', models.CharField(max_length=20, verbose_name='使用者編號')),
                ('APPID', models.IntegerField(verbose_name='app編號')),
                ('C_AMOUNT', models.IntegerField(verbose_name='花費的碳稅')),
                ('GPOINT', models.IntegerField(verbose_name='獲得的點數')),
                ('AMOUNT', models.IntegerField(verbose_name='消費總金額')),
                ('CDATE', models.DateTimeField(default=django.utils.timezone.now, verbose_name='成立時間')),
            ],
        ),
        migrations.CreateModel(
            name='CLIST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ORDID', models.CharField(max_length=20, verbose_name='訂單編號')),
                ('SMELL', models.CharField(max_length=20, verbose_name='香味選擇')),
                ('DMETHOD', models.CharField(max_length=20, verbose_name='送洗方式')),
                ('BAGNUM', models.IntegerField(default=1, verbose_name='袋數')),
                ('PRICE', models.IntegerField(default=0, verbose_name='總金額')),
                ('TIME', models.IntegerField(default=0, verbose_name='總時長')),
                ('FMODE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sa_final.fmode')),
                ('LMODE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sa_final.lmode')),
                ('WMODE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sa_final.wmode')),
            ],
        ),
    ]
