# Generated by Django 4.1.4 on 2023-01-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sa_final', '0026_delivery_order_clist'),
    ]

    operations = [
        migrations.CreateModel(
            name='USER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USERID', models.CharField(max_length=100)),
                ('ACCESSCODE', models.CharField(max_length=100)),
            ],
        ),
    ]
