# Generated by Django 4.1.4 on 2023-01-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sa_final', '0027_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='USERID',
            new_name='MEMID',
        ),
        migrations.AlterField(
            model_name='bag',
            name='MEMID',
            field=models.CharField(default=0, max_length=40, verbose_name='使用者編號'),
        ),
        migrations.AlterField(
            model_name='order',
            name='MEMID',
            field=models.CharField(max_length=40, verbose_name='使用者編號'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='ADDRESS',
            field=models.CharField(max_length=40, verbose_name='地址'),
        ),
    ]
