# Generated by Django 4.1.4 on 2023-01-12 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sa_final', '0028_rename_userid_user_memid_alter_bag_memid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='MEMID',
            new_name='USERID',
        ),
    ]
