# Generated by Django 4.1.4 on 2023-01-12 13:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sa_final', '0029_rename_memid_user_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='solve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QTYPE', models.CharField(max_length=20, verbose_name='問題類型')),
                ('QTEXT', models.CharField(max_length=200, verbose_name='問題描述')),
            ],
        ),
        migrations.RemoveField(
            model_name='clist',
            name='DMETHOD',
        ),
        migrations.AlterField(
            model_name='clist',
            name='SMELL',
            field=models.CharField(max_length=20, verbose_name='香味'),
        ),
        migrations.AlterField(
            model_name='clist',
            name='TIME',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='完成時間'),
        ),
    ]
